#!/bin/bash

# find all files with .routes.ts extension
# so we can load all routes
echo "// DO NOT EDIT THIS FILE" > src/autoload.ts
echo "// THIS FILE IS AUTOGENERATED" >> src/autoload.ts
echo "" >> src/autoload.ts
echo "import Container from \"typedi\";" >> src/autoload.ts

classes=()
files=$(find . -name "*.routes.ts")
for file in $files
do
    content=$(cat $file)
    if [ -z "$content" ]
    then
        continue
    fi

    class=$(echo $content | sed -n -e 's/^.*export default class //p' | sed -n -e 's/ implements.*//p')
    echo "import ${class} from \".$file\";" >> src/autoload.ts

    classes+=($class)
done
classes=$(printf ",%s" "${classes[@]}")
classes=${classes:1}

echo "" >> src/autoload.ts
echo "Container.import([${classes}]);" >> src/autoload.ts

echo "Autoload file generated!"