version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: bunts
      POSTGRES_DB: bunts
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - 1234:1234