#!/bin/bash

# find all files with .routes.ts extension
# so we can load all routes
echo "// DO NOT EDIT THIS FILE" > src/db/entities.ts
echo "// THIS FILE IS AUTOGENERATED" >> src/db/entities.ts
echo "" >> src/db/entities.ts

classes=()
files=$(find . -name "*.model.ts")
for file in $files
do
    content=$(cat $file)
    if [ -z "$content" ]
    then
        continue
    fi

    class=$(echo $content | sed -n -e 's/^.*export class //p' | sed -n -e 's/ extends.*//p')
    echo "import { ${class} } from \"../.$file\";" >> src/db/entities.ts

    classes+=($class)
done
classes=$(printf ",%s" "${classes[@]}")
classes=${classes:1}

echo "" >> src/db/entities.ts
echo "export const entities = [${classes}];" >> src/db/entities.ts

echo "Entities file generated!"